#!/usr/bin/python3
"""Module that factorize as many numbers"""
from sys import argv


def factorize(value):
    """"print a product of an integer > 1"""
    i = 2

    if value < 2:
        print("Value provided is less than 2.(",value,")")
        return
    print("***********************************************************************************************")
    print("Current Value -->",value)
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
    print("***********************************************************************************************")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(value)
            line = file.readline()
except:
    pass
